[package]
name = "lonewolf-xmpp"
description = "XMPP stanza and JID types for Lonewolf"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bumpalo.workspace = true
icu_properties.workspace = true
idna.workspace = true
precis-profiles.workspace = true
