[workspace]
members = ["crates/lonewolf", "crates/lonewolf-util", "crates/lonewolf-xmpp"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
compio-io = { version = "0.10.1", default-features = false, features = ["compat"] }
crossbeam-queue = "0.3.12"
crossbeam-utils = "0.8.21"
futures-executor = "0.3.34"
icu_properties = { version = "2.3.0", default-features = false, features = ["compiled_data"] }
idna = "1.1.0"
lonewolf-util = { path = "crates/lonewolf-util" }
lonewolf-xmpp = { path = "crates/lonewolf-xmpp" }
precis-profiles = { version = "0.2.0", default-features = false }
quick-xml = { version = "0.41.0", default-features = false, features = ["async-tokio"] }
tokio = { version = "1.53.1", default-features = false, features = ["io-util"] }
tokio-util = { version = "0.7.19", default-features = false, features = ["compat"] }
