[package]
name = "lonewolf"
description = "A modern and highly efficient XMPP server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
clap.workspace = true
lonewolf-core.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(unix)'.dev-dependencies]
nix.workspace = true
