[package]
name = "lonewolf"
description = "XMPP server written in Rust"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
clap.workspace = true
lonewolf-xmpp.workspace = true
serde.workspace = true
serde-saphyr.workspace = true

[dev-dependencies]
tempfile.workspace = true
