[package]
name = "lonewolf-util"
description = "Shared utilities for Lonewolf"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-lock.workspace = true
blocking.workspace = true
crossbeam-queue.workspace = true
crossbeam-utils.workspace = true

[dev-dependencies]
futures-executor.workspace = true

[[bench]]
name = "pool"
harness = false
